### ISSUE TITLE
Letsencrypt-vesta generate errors on CentOS

### ISSUE THREAD

**Issue by crarchile** [interbrite/letsencrypt-vesta#16]
## I am running the Letsencrypt-vesta  on CentOS Release 7 64 Bits and I get the following error when run it:

Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
with the specifics so we can fix it:

https://github.com/erikrose/peep/issues/new

Here are some particulars you can copy and paste into the bug report:

---

peep: (3, 1, 1)
python: '2.6.6 (r266:84292, Jul 23 2015, 15:22:56) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]'
pip: '1.4.1'
Command line:  ['/tmp/tmp.vAmVmyO0lC/peep.py', 'install', '-r', '/tmp/tmp.vAmVmyO0lC/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 967, in <module>
    exit(main())
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 939, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 864, in peep_install
    for path in req_paths))
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 864, in <genexpr>
    for path in req_paths))
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 841, in downloaded_reqs_from_path
    _parse_requirements(path, finder)]
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 422, in __init__
    self.**class** = self._class()
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 701, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 331, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 657, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 331, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.vAmVmyO0lC/peep.py", line 610, in _downloaded_filename
    link = self._link() or self._finder.find_requirement(self._req, upgrade=False)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/index.py", line 201, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/index.py", line 554, in _get_page
    return HTMLPage.get_page(link, req, cache=self.cache)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/index.py", line 671, in get_page
    resp = urlopen(url)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/download.py", line 176, in __call__
    response = self.get_opener(scheme=scheme).open(url)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/download.py", line 155, in https_open
    return self.do_open(self.specialized_conn_class, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1163, in do_open
    r = h.getresponse()
  File "/usr/lib64/python2.6/httplib.py", line 1012, in getresponse
    response.begin()
  File "/usr/lib64/python2.6/httplib.py", line 404, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.6/httplib.py", line 368, in _read_status
    raise BadStatusLine(line)
BadStatusLine

---

Let's encrypt returned an error status.  Aborting.

Someone know how can I solve it ?

**Comment by getin2** [comment]
update python to newer version 2.78 or above and try again saw it somewhere, also stop nginx running whilst installing as it uses port 80

**Comment by user67x** [comment]
Hello,

I have Python in 2.7.6 version, on a Ubuntu LTS. Is it adequate?

//EDIT : The Let's Encrypt client currently requires Python 2.7.
Nice

**Comment by jpitoniak** [comment]
Sounds like this was due to the incorrect version of Python being used and that you've resolved it, so I'm closing the issue.  Feel free to reopen if you're still having issues.
